"""add edited_at to task_comment

Revision ID: 6e5d9e91f41a
Revises: d21060d2754d
Create Date: 2026-01-30 11:31:05.115284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5d9e91f41a'
down_revision: Union[str, Sequence[str], None] = 'd21060d2754d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comment', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_comment', 'edited_at')
    # ### end Alembic commands ###
