"""Make sprint_id and assigned_user_id nullable in task

Revision ID: b77b26a332e4
Revises: 82706dc0c20e
Create Date: 2026-01-23 11:57:31.996180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77b26a332e4'
down_revision: Union[str, Sequence[str], None] = '82706dc0c20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
