"""add cascade delete to relations

Revision ID: d21060d2754d
Revises: dea12fac820c
Create Date: 2026-01-29 10:27:44.849102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21060d2754d'
down_revision: Union[str, Sequence[str], None] = 'dea12fac820c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activation_tokens_user_id_fkey'), 'activation_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'activation_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('decisions_project_id_fkey'), 'decisions', type_='foreignkey')
    op.drop_constraint(op.f('decisions_chosen_by_fkey'), 'decisions', type_='foreignkey')
    op.drop_constraint(op.f('decisions_task_id_fkey'), 'decisions', type_='foreignkey')
    op.create_foreign_key(None, 'decisions', 'users', ['chosen_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'decisions', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'decisions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('objective_sprint_id_fkey'), 'objective', type_='foreignkey')
    op.drop_constraint(op.f('objective_project_id_fkey'), 'objective', type_='foreignkey')
    op.create_foreign_key(None, 'objective', 'sprint', ['sprint_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'objective', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_user_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_invitation_invited_user_id_fkey'), 'projects_invitation', type_='foreignkey')
    op.create_foreign_key(None, 'projects_invitation', 'users', ['invited_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sprint_project_id_fkey'), 'sprint', type_='foreignkey')
    op.create_foreign_key(None, 'sprint', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_sprint_id_fkey'), 'task', type_='foreignkey')
    op.drop_constraint(op.f('task_project_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'sprint', ['sprint_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_blocker_task_id_fkey'), 'task_blocker', type_='foreignkey')
    op.create_foreign_key(None, 'task_blocker', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_comment_task_id_fkey'), 'task_comment', type_='foreignkey')
    op.create_foreign_key(None, 'task_comment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_status_history_task_id_fkey'), 'task_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'task_status_history', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('task_status_history_task_id_fkey'), 'task_status_history', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_comment', type_='foreignkey')
    op.create_foreign_key(op.f('task_comment_task_id_fkey'), 'task_comment', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_blocker', type_='foreignkey')
    op.create_foreign_key(op.f('task_blocker_task_id_fkey'), 'task_blocker', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_project_id_fkey'), 'task', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('task_sprint_id_fkey'), 'task', 'sprint', ['sprint_id'], ['id'])
    op.drop_constraint(None, 'sprint', type_='foreignkey')
    op.create_foreign_key(op.f('sprint_project_id_fkey'), 'sprint', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'projects_invitation', type_='foreignkey')
    op.create_foreign_key(op.f('projects_invitation_invited_user_id_fkey'), 'projects_invitation', 'users', ['invited_user_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_user_id_fkey'), 'project_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.create_foreign_key(op.f('objective_project_id_fkey'), 'objective', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('objective_sprint_id_fkey'), 'objective', 'sprint', ['sprint_id'], ['id'])
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.create_foreign_key(op.f('decisions_task_id_fkey'), 'decisions', 'task', ['task_id'], ['id'])
    op.create_foreign_key(op.f('decisions_chosen_by_fkey'), 'decisions', 'users', ['chosen_by'], ['id'])
    op.create_foreign_key(op.f('decisions_project_id_fkey'), 'decisions', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'activation_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('activation_tokens_user_id_fkey'), 'activation_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
